### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by hectorcuper82** [Diablo-D3/DiabloMiner#84]
I launch DiabloMiner in Eclipse with this parameter: -l http://username:password@localhost:8332

I'm always seeing this in my terminal:

ERROR: Cannot connect to localhost: Connection refused: connect

Am I doing something wrong?

I have an account on bitcoinwallet.com. is it good?

please give me an example of a line to configure the proxy?

**Comment by Diablo-D3** [comment]
DiabloMiner is no longer under development, and does not speak the new miner protocol.

Use cgminer instead.
