### ISSUE TITLE
Cannot connect to bitcoin. Method not found

### ISSUE THREAD

**Issue by poklonnik518** [Diablo-D3/DiabloMiner#88]
Hi guys, I'm on CentOS 7. Running `bitcoind`. I've put `rpcuser` and `rpcpassword` settings the the `~/.bitcoin/bitcoin.conf` When I'm running `./DiabloMiner-Linux.sh -u user -p pass` i'm getting the following error:
```
[5/31/17 3:37:51 AM] ERROR: Cannot connect to localhost: Bitcoin returned error message: Method not found
```
What am i doing wrong?

**Comment by allquixotic** [comment]
> What am i doing wrong?

You're not searching the closed issues of many duplicates of this and similar questions.

https://github.com/Diablo-D3/DiabloMiner/issues/86#issuecomment-289354314

 > Per #84 (comment)

 > DiabloMiner is no longer under development, and does not speak the new miner protocol.
 > Use cgminer instead.

**Comment by poklonnik518** [comment]
@allquixotic got it.
