### ISSUE TITLE
document usage better

### ISSUE THREAD

**Issue by ashtonhogan** [Diablo-D3/DiabloMiner#89]
My goal:

Using Ubuntu, I want to mine with my GPU using a worker on my multipool.us (stratum+tcp://us.multipool.us:3334) account

How do I do this?

I've tried:

`./DiabloMiner-Linux.sh -l username:password@us.multipool.us:3358`

But I get:

> Connecting to: http://us.multipool.us:3358/						 
> Exception in thread "main" java.awt.AWTError: Assistive Technology not found: org.GNOME.Accessibility.AtkWrapper
> 

So I'm pretty sure I'm doing something wrong...

**Comment by allquixotic** [comment]
> So I'm pretty sure I'm doing something wrong...

You are. You're using unmaintained, unsupported software. 

From https://github.com/Diablo-D3/DiabloMiner/issues/88#issuecomment-305114354

 > What am i doing wrong?

You're not searching the closed issues of many duplicates of this and similar questions.

https://github.com/Diablo-D3/DiabloMiner/issues/86#issuecomment-289354314

 > Per #84 (comment)

 > DiabloMiner is no longer under development, and does not speak the new miner protocol.
 > Use cgminer instead.

**Comment by ashtonhogan** [comment]
@allquixotic recommending a different repo is not a solution that fixes this repo

**Comment by Diablo-D3** [comment]
His suggestion is correct. There is no fix for this repo because the mining client protocol changed and I opted to pass the baton to cgminer instead of fixing it up myself. In addition, I did not want to bother adding FPGA/ASIC support which would be very nasty to do in Java, which was something that had to be done to keep DiabloMiner relevant.

**Comment by ashtonhogan** [comment]
@Diablo-D3 what about mining other cryptocurrencies besides bitcoin? It's not always the most profitable experience to mine bitcoins

**Comment by allquixotic** [comment]
Most altcoins based on the Bitcoin blockchain very closely follow the Bitcoin price. The absolute quantities of coin may differ, but if 1 RandomCoin is 1% of the RandomCoin total available coin, and 1% of BitCoin is worth, say, $1 billion US, then 1 RandomCoin would also be worth around $1 billion US.

So, mining altcoins (other than Ethereum) will be no more efficient with your GPU (vs. FPGAs/ASICs) than mining Bitcoin.

Coins that aren't based on the Bitcoin blockchain algorithms wouldn't work with DiabloMiner anyway.

**Comment by ashtonhogan** [comment]
@allquixotic well new coins generally have far less difficulty than Bitcoin but anyway, I don't want to get into a debate over mining in general. My point is that there still could be a use for this repo, you don't have to kill it

**Comment by Diablo-D3** [comment]
The draw of alt-coins is that they don't use SHA256. DiabloMiner has only ever supported SHA256.

People are welcome to fork DiabloMiner (or more preferably, fork or patch cgminer) to support other hashes for other coins, but I have no interest in it. This repo continues to exist only for historical reasons.

**Comment by nguyentienmanh260111** [comment]
ok
